/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _DetailResultRoute } from '../pages/detail-result';
import { Route as _IndexRoute } from '../pages/';
import { Route as _ResultRoute } from '../pages/result';
import { Route as _TestRoute } from '../pages/test';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/detail-result': (typeof _DetailResultRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/result': (typeof _ResultRoute)['_inputType'];
    '/test': (typeof _TestRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/detail-result': (typeof _DetailResultRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/result': (typeof _ResultRoute)['_outputType'];
    '/test': (typeof _TestRoute)['_outputType'];
  }
}
